### ISSUE TITLE
.wim not loading into program. When I try to load the install.wim, the program goes unresponsive and stops working.

### ISSUE THREAD

**Issue by greentractor202** [WOA-Project/WOA-Deployer-Rpi#14]
Please use the "Preview" tab above to view this message if you are seeing this in the new issue text box.

Please note that this is a **WoA Deployer** issue tracker, use this issue tracker only for the WoA Deployer related bugs.

Please open ticket in [Raspberry Pi WOA forum](https://discourse.pi64.win/) or [Raspberry Pi WOA Telegram group](https://t.me/joinchat/ACWtm01aRdQuRAu1d3kW7Q) for anything else, such as:

- Reporting bugs of other tools, drivers, etc.
- Asking for help

# Please remove the text above before opening an issue.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Log file**
Please put your log file here (just drag&drop it).

**Comment by cleveHEX** [comment]
Didn't fill the form, closing this issue. DO NOT OPEN ANOTHER ISSUE, you may edit this one.
