### ISSUE TITLE
Mount ISO files

### ISSUE THREAD

**Issue by BelleNottelling** [WOA-Project/WOA-Deployer-Rpi#19]
To whoever wrote the issue template, I apologize for deleting all of it. 

Anyways,the title says it, I think it would be great if this tool could mount and extract the WIM from an ISO file, which would save new users some confusion, and experienced users a manual step.

I'm not sure of all the different ways to do this, but I do know 7zip can extract an ISO, and if I remember correctly you can even specify a specif file to extract so skips all the rest.

**Comment by cleveHEX** [comment]
Already here: https://github.com/WOA-Project/WOA-Deployer-Platform/projects/1#card-17753867

**Comment by BelleNottelling** [comment]
My apologies, I didn't realize that was there!
