### ISSUE TITLE
Discord

### ISSUE THREAD

**Issue by ghost** [WOA-Project/WOA-Deployer-Rpi#2]
Can it be possible to have a discord community 
I can do one for you if you want

**Comment by SuperJMN** [comment]
Sorry, we already have a community in [Telegram](https://t.me/joinchat/ACWtm01aRdQuRAu1d3kW7Q) :)

**Comment by ghost** [comment]
Can ti be possible to have one in discord I can make everythings

**Comment by ghost** [comment]
I think it would be better than telegram
