### ISSUE TITLE
error code: 1392

### ISSUE THREAD

**Issue by DennisSentler** [WOA-Project/WOA-Deployer-Rpi#21]
so, today this error code was shown to me, after flashing about 50% of the image.

I'm using Win 10, the WOA is on 2.1.0 and I wanted to flash Windows 10 Home build 17134.
The SD Card I was using got 32GB.
Sorry but I did not find any information about this error code.

**Comment by cleveHEX** [comment]
You just erased and did not fill the bug report form.
