### ISSUE TITLE
Could not create ISO

### ISSUE THREAD

**Issue by biconix** [WOA-Project/WOA-Deployer-Rpi#22]
I was able to download the "creatingISO_17763.346_en-us_arm64_Professional.cmd" file but was not able to execute it.
after it downloads a bunch of files, the screen clears and I get an error that says: "Error work script.".

Am I leaving something out?

(I have downloaded to script file to c:\temp\WindowsARM folder)

**Comment by dylanmc** [comment]
I am having the same problem, and was about to log this here when I found this closed ticket. Maybe the process for getting the ARM image is no longer working?
