### ISSUE TITLE
DISM exited with code 2

### ISSUE THREAD

**Issue by lmzumpano** [WOA-Project/WOA-Deployer-Rpi#24]
Got this Code Error (2) trying to Deploy the Windows 10 on my SD Card, i'm using on a Windows 10 Pro fully updated (Windows Update message says that)

.wim is Windows 10 pro build 17763

**Log file**
[log.txt](https://github.com/WOA-Project/WOA-Deployer-Rpi/files/2946012/log.txt)

**Comment by SuperJMN** [comment]
DISM related issues aren't because of WOA Deployer most of times. Please review this info and check what's wrong.

DISM Error: 2

An initialization error occurred.
For more information, review the log file.

The DISM log file can be found at C:\Windows\Logs\DISM\dism.log
