### ISSUE TITLE
DISM exited with code 5

### ISSUE THREAD

**Issue by Deltadart** [WOA-Project/WOA-Deployer-Rpi#25]
Hey, tried to deploy with the tool and got this error message. 

As reference, I'm using the 1809 ARM version updated in March.
![Iso version](https://user-images.githubusercontent.com/48517625/54278234-33d4a500-4568-11e9-8750-69031ff33762.png)

Here's the error code screenshot

![Error Code 5](https://user-images.githubusercontent.com/48517625/54278267-464ede80-4568-11e9-9a44-2273bd0bd32f.png)

Here's the Log file 

[Log-20190313.txt](https://github.com/WOA-Project/WOA-Deployer-Rpi/files/2961405/Log-20190313.txt)

**Comment by SuperJMN** [comment]
Problems with .WIM files aren't a problem with WOA Deployer itself. Please, regenerate your .iso (wim) again. Maybe it's because of file corruption.
