### ISSUE TITLE
Miultilanguage GUI - How to enable/revise it

### ISSUE THREAD

**Issue by bovirus** [WOA-Project/WOA-Deployer-Rpi#27]
How can change language for GUI?

How to revise the language files for GUI?

**Comment by cleveHEX** [comment]
There is no multi-language GUI.

**Comment by bovirus** [comment]
Why not?
For me could be an interesting improvements.

**Comment by cleveHEX** [comment]
I don't see any benefit from this being implemented, it's on TO-DO, but with lowest priority. We are working on more important things at the moment.

**Comment by bovirus** [comment]
The benefit is very simple.
As for amy other sofwtare.
A lot of people doesn't know English and has more familiarity with interface in native language.
