### ISSUE TITLE
Error on Deploy: "Could not find a part of the path 'C:\WINDOWS\system32\Scripts\Deployment.txt'"

### ISSUE THREAD

**Issue by eximiusvir** [WOA-Project/WOA-Deployer-Rpi#28]
**Describe the bug**
After following the steps to generate the WOA ISO ([link](https://github.com/WOA-Project/guides/blob/master/GettingWOA.md)) and proceeding to exercise the WOA Deployer for Raspberry PI (2.11), when I click Deploy, I receive the error: "Could not find a part of the path 'C:\WINDOWS\system32\Scripts\Deployment.txt'.

**To Reproduce**

1. Go to https://github.com/WOA-Project/guides/blob/master/GettingWOA.md and follow the steps to download an ARM64 ISO installer image.
2. Go to https://github.com/WOA-Project/WOA-Deployer-Rpi and download the latest version ([link](https://github.com/WOA-Project/WOA-Deployer-Rpi/releases/latest))
3. Mount the ISO image (E:\)
3. Extract **WOA.Deployer** to C:\temp\WOA.Deployer
4. In **File Explorer**, navigate to C:\temp\WOA.Deployer and double click **WoaDeployer.exe**
5. In the **DRIVE SELECTION** drop-down, select your MicroSD card (mine is 64GB)
6. In the **WINDOWS IMAGE**, specify the path E:\sources\install.wim
7. Note the drop-down below the path will populate with: **1** Windows 10 Pro build 17763
8. Click **Deploy**
9. Click **OK** to **Confirm deployment**
10. Note the displayed error:
**Error
Could not find a part of the path 'C:\WINDOWS\system32\Scripts\Deployment.txt'**

**Expected behavior**
Deployment would proceed as expected

![2019-04-06_11-57-42](https://user-images.githubusercontent.com/17688650/55673928-4094a200-5863-11e9-8e0c-a6f5e469d413.jpg)

**Comment by cleveHEX** [comment]
Check your deployer/redownload it, your scripts folder is probably missing. If issue persists, comment.

**Comment by vimalswaroopj** [comment]
run the WOA software as administrator. First I tried many times without using Run as Administrator option. Later I tried with it and it worked for me.

**Comment by Cycododge** [comment]
For myself, the issue was caused by doing a `*.exe` search in the deployer folder, and attempting to run it from the results view. Clear the search and locate it manually.
