### ISSUE TITLE
Bad link in README.md

### ISSUE THREAD

**Issue by geeksfn** [WOA-Project/WOA-Deployer-Rpi#3]
The link is not active for downloading the latest version, https://github.com/SuperJMN/WoA-Installer/releases/latest. 

Thanks!

**Comment by SuperJMN** [comment]
You're checking the wrong address :) **WoA Installer** is now deprecated

The application you're looking for is WOA Deployer for Raspberry Pi :)
https://github.com/WOA-Project/WOA-Deployer-Rpi/releases

**Comment by mongonta0716** [comment]
Hi, @SuperJMN 

The link of README.md is incorrect.

Thanks.

**Comment by SuperJMN** [comment]
You're right! thanks for telling me! it's fixed now.
