### ISSUE TITLE
Wi-Fi driver

### ISSUE THREAD

**Issue by BaRRaKudaRain** [WOA-Project/WOA-Deployer-Rpi#33]
I would love to have the program inject a driver for Wi-Fi. Is drivers already written?

**Comment by SuperJMN** [comment]
No, sorry. I think there aren't any drivers for Wi-Fi, sorry. Also, I don't think they will be any in the foreseeable future.

**Comment by BaRRaKudaRain** [comment]
Very bad... I wish I could write them...
