### ISSUE TITLE
Crashes immediately when pointing to install.wim file, not every comp shows harddisk/usb devices

### ISSUE THREAD

**Issue by ghost** [WOA-Project/WOA-Deployer-Rpi#39]
1. On some computers when loading the program it will not show up any usb (harddisk) device
2. Program crashes immediately after pointing to location of install.wim... it tries to load and *bam* .. crash
 Windows Event Viewer writes errors about kernelbase.dll
and Framework error below: 

Toepassing: WoaDeployer.exe
Framework-versie: v4.0.30319
Beschrijving: het proces is beëindigd als gevolg van een onverwerkte uitzondering.
Uitzonderingsinformatie: System.InvalidOperationException
   bij MahApps.Metro.Controls.Dialogs.DialogCoordinator.GetMetroWindow(System.Object)
   bij MahApps.Metro.Controls.Dialogs.DialogCoordinator.ShowMessageAsync(System.Object, System.String, System.String, MahApps.Metro.Controls.Dialogs.MessageDialogStyle, MahApps.Metro.Controls.Dialogs.MetroDialogSettings)
   bij Deployer.Gui.Common.Services.Dialog.ShowAlert(System.Object, System.String, System.String)
   bij Deployer.Raspberry.Gui.ViewModels.WimPickViewModel.<.ctor>b__4_2(System.Exception)
   bij System.Reactive.AnonymousSafeObserver`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].OnNext(System.__Canon)
   bij System.Reactive.Sink`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].ForwardOnNext(System.__Canon)
   bij System.Reactive.IdentitySink`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].OnNext(System.__Canon)
   bij System.Reactive.SafeObserver`1+WrappingSafeObserver[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].OnNext(System.__Canon)
   bij System.Reactive.Sink`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].ForwardOnNext(System.__Canon)
   bij System.Reactive.ObserveOnObserverNew`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].DrainStep(System.Collections.Concurrent.ConcurrentQueue`1<System.__Canon>, Boolean)
   bij System.Reactive.ObserveOnObserverNew`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].DrainShortRunning(System.Reactive.Concurrency.IScheduler)
   bij System.Reactive.ObserveOnObserverNew`1+<>c[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].<.cctor>b__20_1(System.Reactive.Concurrency.IScheduler, System.Reactive.ObserveOnObserverNew`1<System.__Canon>)
   bij System.Reactive.Concurrency.DispatcherScheduler+<>c__DisplayClass12_0`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].<Schedule>b__0()
   bij System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   bij System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   bij System.Windows.Threading.DispatcherOperation.InvokeImpl()
   bij System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   bij MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   bij System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   bij System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   bij System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   bij MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   bij System.Windows.Threading.DispatcherOperation.Invoke()
   bij System.Windows.Threading.Dispatcher.ProcessQueue()
   bij System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   bij MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   bij MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   bij System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   bij System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   bij System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   bij MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   bij MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   bij System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   bij System.Windows.Threading.Dispatcher.PushFrame(System.Windows.Threading.DispatcherFrame)
   bij System.Windows.Application.RunDispatcher(System.Object)
   bij System.Windows.Application.RunInternal(System.Windows.Window)
   bij System.Windows.Application.Run(System.Windows.Window)
   bij Deployer.Raspberry.Gui.App.Main()

**Comment by frumbert** [comment]
Wow, you get a crash?? All I get is the spinning wheel of doom.

The log is pretty nondescript

```
2019-06-25 18:46:54.401 +10:00 [Verbose] Default directory for WimFolder has been set to "C:\"
2019-06-25 18:46:54.405 +10:00 [Verbose] Trying to load WIM metadata file at '"C:\install.wim"'
2019-06-25 18:46:54.473 +10:00 [Verbose] Getting WIM stream
2019-06-25 18:46:54.475 +10:00 [Verbose] (WIM) Finding Magic Bytes...
2019-06-25 18:46:54.475 +10:00 [Verbose] (WIM) Found Magic Bytes at 0
2019-06-25 18:46:54.475 +10:00 [Verbose] (WIM) Finding WIM XML Data...
2019-06-25 18:46:54.475 +10:00 [Verbose] (WIM) Found WIM XML Data at 002
2019-06-25 18:49:50.284 +10:00 [Verbose] The '"C:\"' exists
2019-06-25 18:49:54.049 +10:00 [Verbose] Default directory for WimFolder has been set to "C:\"
2019-06-25 18:49:54.052 +10:00 [Verbose] Trying to load WIM metadata file at '"C:\install.wim"'
2019-06-25 18:49:54.069 +10:00 [Verbose] Getting WIM stream
2019-06-25 18:49:54.069 +10:00 [Verbose] (WIM) Finding Magic Bytes...
2019-06-25 18:49:54.070 +10:00 [Verbose] (WIM) Found Magic Bytes at 0
2019-06-25 18:49:54.070 +10:00 [Verbose] (WIM) Finding WIM XML Data...
2019-06-25 18:49:54.070 +10:00 [Verbose] (WIM) Found WIM XML Data at 002
```

The drive selection takes about 2 minutes before it sees my usb3 microsd reader, but eventually that bit is fine.

(windows 10 home, v 1903)

**Comment by ghost** [comment]
I fixed it by installing a fresh Windows 10 (Pro, version may 2019) .. Now all works flawless :)
