### ISSUE TITLE
Drive selection problem

### ISSUE THREAD

**Issue by ELHAMLAOUI** [WOA-Project/WOA-Deployer-Rpi#4]
Hi,
I have downloaded WoA deployer in windows and i have a problem selecting the drive as is it's always in loading form even afer 1h.
Can you help me with this issue.
Thanks

**Comment by SuperJMN** [comment]
Try to disconnect any removable drives. It could be corrupted drive. Or simply try with another PC.

**Comment by ELHAMLAOUI** [comment]
Thanks, it's works on another machine.

**Comment by Krutonium** [comment]
I'm getting this too.
