### ISSUE TITLE
Raspberry pi 4 ?

### ISSUE THREAD

**Issue by squadtak** [WOA-Project/WOA-Deployer-Rpi#41]
it can?
Is it comfortable if it moves?

**Comment by SteveALee** [comment]
My thoughts too. Just ordered a 2GB board so will be able to play soon

**Comment by SteveALee** [comment]
Doesn't work for me. I followed the intructions to the letter using the latest Insiders Build (could not find 1903). The Pi never boots. Just flashes the green LED on a "4 flash - pause on" cycle.

* I have a 64GB card - so FAT32 formatted it first
* I could not eject the card from windows as it was in use but I was unable to find what was locking it.
* I'm not sure if all the partitions on the card are correct as one is empty - #43

**Comment by SteveALee** [comment]
It seems [TOM's hardward failed to get it to boot](https://www.tomshardware.com/reviews/raspberry-pi-4-b,6193.html) but do not say how they deployed

And more ferreting around indicates different Chipset, new UEFI will be needed and the [boot loader is different](https://www.raspberrypi.org/documentation/hardware/raspberrypi/booteeprom.md)

Thus there's work to be done before it works :(

**Comment by squadtak** [comment]
Just wait for support?

**Comment by SuperJMN** [comment]
Sorry, guys. This isn't going to happen unless the OEM vendors, primarily Qualcomm, releases drivers for ARM64. We can make a campaign for that, but if we don't have drivers, we're sold.

**Comment by SteveALee** [comment]
Ah, so it’s a different architecture? I hadn’t realised that.

**Comment by SteveALee** [comment]
Looks like [some are available](https://discourse.pi64.win/t/status-of-the-arm64-device-drivers-as-of-12-feb-2019/38) already

**Comment by SuperJMN** [comment]
Those drivers are for Raspberry Pi 3. If the 4 has different devices, it will require different drivers, too.

**Comment by SuperJMN** [comment]
@SteveALee they are the same architecture: ARM64.

**Comment by SteveALee** [comment]
@SuperJMN ah OK, I mis understood when you said "releases drivers for ARM64". Anyway I guess that table on pi64 will need a brand new column for pi 4 chips :)

**Comment by openlewa** [comment]
Comment from SteveALee + my Comment.
>   Doesn't work for me. I followed the intructions to the letter using the latest Insiders Build (could 
>   not find 1903). The Pi never boots. Just flashes the green LED on a "4 flash - pause on" cycle.
> 
>     * I have a 64GB card - so FAT32 formatted it first
> 
>     * I could not eject the card from windows as it was in use but I was unable to find what was locking it.
> 
>     * I'm not sure if all the partitions on the card are correct as one is empty - #43

I have the same problem. + After the format of the SDcard with WOA the Windows disk management cant format the SDcard and cant open it as a folder, the ''MiniTool Partition Wizard'' can help you.
You need to create a exFAT Volume and then use the ''guiformat from ridgecrop'' to create a FAT32 partition.

> The Pi never boots. Just flashes the green LED on a "4 flash - pause on" cycle.

Is the SPI EEPROM corrupted?

>     * I could not eject the card from windows as it was in use but I was unable to find what was locking it.
You can shutdown your Computer and then eject the SDcard

**Comment by hwangjr** [comment]
so, any progress for pi 4? guys.

**Comment by linxu** [comment]
not support pi4?

**Comment by squadtak** [comment]
yep not supported. But I think they are working hard for support. Let's wait a little longer.

**Comment by squadtak** [comment]
Apparently the driver is not yet supported.

**Comment by georgewoodall82** [comment]
Does it work on raspberry pi 3B+ or 3B?

**Comment by openlewa** [comment]
> 
> 
> Does it work on raspberry pi 3B+ or 3B?

https://github.com/WOA-Project/WOA-Deployer-Rpi#requirements

**Comment by openlewa** [comment]
Did you see this?

Support for the Raspberry Pi 4
https://github.com/andreiw/RaspberryPiPkg/issues/130


lampone_build.sh
https://github.com/andreiw/lampone/blob/master/lampone_build.sh

Pi4 Firmware Task Force 
https://github.com/pftf

**Comment by lseurttyuu** [comment]
Somebody managed to run Windows 10 ARM on RPi4, here's the news:

https://www.windowslatest.com/2020/01/27/windows-10-arm-on-raspberry-pi-4/

**Comment by CornyjK** [comment]
NO NOT OPEN ANOTHER DUPLICATE REQUESTS, WE CAN'T RIGHT NOW.
