### ISSUE TITLE
How to get it offreg.dll file？

### ISSUE THREAD

**Issue by eguotangseng** [WOA-Project/WOA-Deployer-Rpi#46]
I run aria2_download_windows.cmd
ERROR: Can not open output file : 拒绝访问。 : .\bin\offreg.dll
How to get it offreg.dll file？

**Comment by eguotangseng** [comment]
Status Legend:
(OK):download completed.
==== ERROR ====
Required file offreg.dll is missing.

**Comment by cleveHEX** [comment]
Not a problem of deployer.
