### ISSUE TITLE
Trojan found in WOA.Deployer.Console.zip

### ISSUE THREAD

**Issue by margalex** [WOA-Project/WOA-Deployer-Rpi#5]
Unzipping the WOA.Deployer.Console.zip makes Windows Defender detect this trojan:

https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3aWin32%2fEmali.A!cl&threatid=2147728322

**Comment by cleveHEX** [comment]
I think we can do nothing about this, just whitelist it.

**Comment by margalex** [comment]
Windows Defender reports that WoaDeployer.exe is infected in WOA.Deployer.Console.zip. I didn't get any warning with WOA.Deployer.GUI.zip.

**Comment by cleveHEX** [comment]
Yes, we can do nothing about this currently, just whitelist it.

**Comment by SuperJMN** [comment]
I think somebody tagged the download as malware... all of a sudden, I can't download the .zip!

![image](https://user-images.githubusercontent.com/3109851/53052425-fe73f480-349e-11e9-9895-6fc7e81ea136.png)

I've already sent a removal request to the Windows Defender team:
![image](https://user-images.githubusercontent.com/3109851/53052384-dedccc00-349e-11e9-8554-3a6c7bfc1796.png)

By the way, this is the virustotal scan summary: https://www.virustotal.com/en/file/1bfbe1372b9afcec086645d24f97fe726d7093c1bcfbfec89329fff754b53d97/analysis/1550613259/

Only Windows Defender is reporting it as malware 😒

**Comment by SuperJMN** [comment]
@margalex Can you, please, try again? The Windows Defender team seems to have removed the false positive from it.

They gave me this instructions to "clear" the cached results:

> We have removed the detection. Please follow the steps below to clear cached detection and obtain the latest malware definitions.
> 
> 1. Open command prompt as administrator and change directory to c:\Program Files\Windows Defender 
> 2. Run “MpCmdRun.exe -removedefinitions -dynamicsignatures”

**Comment by margalex** [comment]
@SuperJMN, I tried it again and it's OK now. Thx!

**Comment by cleveHEX** [comment]
> Can you, please, try again? The Windows Defender team seems to have removed the false positive from it.

I expected MS to be much slower 😀
