### ISSUE TITLE
DISM exited with code 1392

### ISSUE THREAD

**Issue by LeanderJDev** [WOA-Project/WOA-Deployer-Rpi#56]
When I run the WOA Deployer v2.1.1 on a 16GB(14.9GB) SD Card to install the Windows 10 Home build 18362, I got the error code 1392. Does anybody know what this means?

![DISM code 1392](https://user-images.githubusercontent.com/60060497/72678336-2f8ce880-3aa5-11ea-8d62-5d19de8e5ffd.PNG)

**Comment by SuperJMN** [comment]
Can you try with a bigger card? DISM errors aren't handled by the Deployer and often indicate problems with the WIM file or the microSD card.

**Comment by LeanderJDev** [comment]
Yes it worked with a bigger card
