### ISSUE TITLE
Error: The read operation failed, see inner exception.

### ISSUE THREAD

**Issue by Nova-Dvorak** [WOA-Project/WOA-Deployer-Rpi#60]
Err... Another problem appeared.
I get a usable install.wim but when deploying, it said "Error: The read operation failed, see inner exception."
I noticed that the problem appeared just after "Downloading UEFI".
May be a problem of my devices?
Log files are below:
[Log-20200201-upload.txt](https://github.com/WOA-Project/WOA-Deployer-Rpi/files/4142074/Log-20200201-upload.txt)

**Comment by Nova-Dvorak** [comment]
I've checked out that my SD Card is not write-protected, and it is formatted with FAT32.

**Comment by Nova-Dvorak** [comment]
Nobody here?

**Comment by SuperJMN** [comment]
Can you please try another card?
________________________________

**Comment by Nova-Dvorak** [comment]
I have only one SD Card now and I cannot go out.... I am trying for one more time.

**Comment by Nova-Dvorak** [comment]
OK... It might be my fault... It seems to work now.Thank you all the same!
