### ISSUE TITLE
Rpi 4 Model B does not boot to UEFI console after successfully deploying Windows 10 on ARM Build 19555

### ISSUE THREAD

**Issue by almahdibakkali96** [WOA-Project/WOA-Deployer-Rpi#61]
I have completed the steps in WOA deployer but can get the RPi to boot to UEFI console, i.e., I don't see anything on the screen when RPi is plugged to both power and micro HDMI.
Please note that microSD was successfully ejected after deployment. 

How can I proceed to troubleshoot this issue? Should I download another version of Windows?

**Comment by SuperJMN** [comment]
Sorry, RPi4 is currently NOT SUPPORTED
