### ISSUE TITLE
Error: End of Central Directory record could not be found.

### ISSUE THREAD

**Issue by amirmallaei** [WOA-Project/WOA-Deployer-Rpi#63]
I could not deploy the win 10 19041
it pop up this error "Error: End of Central Directory record could not be found."
any solution?

**Comment by SuperJMN** [comment]
Try to redeploy.

Details: WOA Deployer automatically downloads the required files. In case your connection is not stable, the files could be corrupted. This is the most probable cause of that message. 
________________________________
