### ISSUE TITLE
Problems with the first boot

### ISSUE THREAD

**Issue by sorbanbela** [WOA-Project/WOA-Deployer-Rpi#7]
Because the old repo was archived, i open a new one here.
So created an SD card with 1809 Windows and core package which has been provided and after probably a hour of initialise progress, the system crashed before the first boot.

I was assuming that will be in the section where i can choose user, and some privacy info .. but it crashed.
I'm using a hungarian version of windows, but the error code is still in international format :)

![img_20190220_155055](https://user-images.githubusercontent.com/20299611/53096583-2ce9e200-3528-11e9-9a73-cbb7945815e8.jpg)

If you have any ideas what i should do to fix the issue, i would be happy.

**Comment by sorbanbela** [comment]
Will try to flash the system again to an another drive (probably will not fix the issue), waiting for an SSD and a SATA->USB adapter with external power.

**Comment by SuperJMN** [comment]
Please, try 17134 to see if it works.

**Comment by sorbanbela** [comment]
Thank you! Yes. With 1803 (17134 build) it works well.
I see that the CPU is downclocked to 0,6 while using windows. I have cooling system on the pi. It is possible to use the CPU on the maximum clock speeds?

**Comment by ghost** [comment]
You could do it in the bios. Search for "Chipset Configuration" and there you will find the option and set it to max.
