### ISSUE TITLE
Problem with "Downloaded\Drivers\BSP Drivers" not found and many "Formating-Drive" windows

### ISSUE THREAD

**Issue by M-Marvin** [WOA-Project/WOA-Deployer-Rpi#81]
I have an problem by deploing Windows on an SD Card.
I use WOA the first time.

I got the same error as described in another issue ("Downloaded\Drivers\BSP Drivers" cannot be found).
The logs and errors are identical, but no clear solution was mentioned, only that you should delete "Downloaded", but where is this "Downloaded"-Folder because, there is no drive name (e.B. "C:") ?

I've followed a guide from the Internet, which pointed out that I may get 1-2 new drives displayed and the formatting requests should cancel, but I'm literally too spammed with new drive windows (but always the same 2 drives, only several times the same window).
[Log-20210601.txt](https://github.com/WOA-Project/WOA-Deployer-Rpi/files/6577415/Log-20210601.txt)
[dism.log](https://github.com/WOA-Project/WOA-Deployer-Rpi/files/6577416/dism.log)

Im using the "Windows Home build 17134" install.wim".

If the one who edits this can German, he should please write it, I use a translator, because my English is not so good.

**Comment by SMNBGR** [comment]
Hallo Marvin!

Hatte das selbe Problem und hab es folgendermaßen gelöst:

![image](https://user-images.githubusercontent.com/56003314/125430076-a10cd2a2-98c8-4a3a-92d2-4282bbe79d64.png)
BSP Drivers Ordner erstellen und dann die richtige Driver ZIP hier saugen -> https://github.com/worproject/RPi-Windows-Drivers/releases und einfach dorthin entpacken. Danach nochmal von vorne und es sollte klappen, habe jedoch selbst eine neuere Version verwendet - hoffe es hilft dir trotzdem.

**Comment by M-Marvin** [comment]
Ok, ich hab es jetzt mit WOR aufgespielt, um es zu testen hab aber 2 Probleme festgestellt, bei denen man mir hier vielleicht auch helfen kann:

1. Der Treiber für den Display Port des RPis (3B) scheint nicht zu funktionieren, zumindest der Touch-betrieb nicht, und das Bild ist fast Quadratisch obwohl der Bildschirm (7'' Standartdisplay für RPi) groß genug wäre.

2. Ich wollte einen Treiber für eine CNC Fräse installieren, die ich darüber steuern wollte, das Programm läuft einwandfrei, aber der Treiber nicht, er heißt CH340SER.EXE für den gleichnamigen USB Chip.
Das Problem ist, er meldet das er nicht auf der Prozessorarchitektur installiert werden kann, gibt es da eventuell einen anderen Treiber?
Ich hab rausgefunden das es ihn für Linux auf dem RPi gibt, aber zu Windows 10 auf RPi hab ich nichts gefunden.

Sollte es eine Lösung dafür geben, würde ich Win 10 nochmal mit WOA aufspielen uns es probieren.
(Aktuell hab ich wieder Raspbian installiert)
