### ISSUE TITLE
WOA Error: "Could not find a part of the path 'C:\WINDOWS\system32\Scripts\Deployment.txt'"

### ISSUE THREAD

**Issue by SanaSuly** [WOA-Project/WOA-Deployer-Rpi#82]
**Describe the bug**
After following the steps to generate the WOA ISO (link) and proceeding to exercise the WOA Deployer for Raspberry PI (2.11), when I click Deploy, I receive the error: "Could not find a part of the path 'C:\WINDOWS\system32\Scripts\Deployment.txt'.

I tryed to search the Scripts file on System32 path but nothing, and i don't know how to get it again.

**To Reproduce**

1. Go to https://github.com/WOA-Project/guides/blob/master/GettingWOA.md and follow the steps to download an ARM64 ISO installer image.
2. Go to https://github.com/WOA-Project/WOA-Deployer-Rpi and download the latest version (link)
3. Mount the ISO image (E:)
4. Extract WOA.Deployer to C:\temp\WOA.Deployer
5. In File Explorer, navigate to C:\temp\WOA.Deployer and double click WoaDeployer.exe
6. In the DRIVE SELECTION drop-down, select your MicroSD card (mine is 64GB)
7. In the WINDOWS IMAGE, specify the path E:\sources\install.wim
8. Note the drop-down below the path will populate with: 1 Windows 10 Pro build 17763
9. Click Deploy
10. Click OK to Confirm deployment
11. Note the displayed error:
      **Error**
      **Could not find a part of the path 'C:\WINDOWS\system32\Scripts\Deployment.txt'**

**Expected behavior**
Deployment would proceed as expected

![image](https://user-images.githubusercontent.com/73762073/120908514-57b1c300-c66b-11eb-9ef5-33c4ad3a4cfa.png)

**I found someone on GH with same problem but not solved, sorry for this double post and thank for your future help !**

**Comment by cleveHEX** [comment]
#28 it was solved there
