### ISSUE TITLE
Install problem

### ISSUE THREAD

**Issue by obisbg** [WOA-Project/WOA-Deployer-Rpi#9]
Can you help me with this message? Thanks
![img_0615_82df8e92](https://user-images.githubusercontent.com/47742497/53124018-ac90a480-355a-11e9-8e93-39eb3fcb1439.jpg)

**Comment by SuperJMN** [comment]
It's a weird problem non related to WOA Deployer. But yes, Some people have faced it. Please, take a look a this: https://twitter.com/murmanz/status/1098215498703986688?s=20
